[versions]
android-compileSdk = "35"
android-targetSdk = "35"
android-minSdk = "24"

android-versionCode = "5"
android-versionName = "1.0.4"

kotlin = "2.1.10"
ksp = "2.1.10-1.0.31"
agp = "8.9.1"

compose-multiplatform = "1.7.0"
compose-activity = "1.10.1"
compose-shadow = "2.0.3"

androidx-appcompat = "1.7.0"
androidx-lifecycle = "2.8.4"
androidx-splashscreen = "1.0.1"
androidx-cardview = "1.0.0"
#androidx-foundation-layout-android = "1.7.8"
#androidx-core-ktx = "1.15.0"
#androidx-material = "1.12.0"
#androidx-constraintlayout = "2.2.0"
#androidx-espresso-core = "3.6.1"
#androidx-test-junit = "1.2.1"

#junit = "4.13.2"

kotlinx-coroutines = "1.10.1"
kotlinx-collections = "0.3.8"
kotlinx-serialization = "1.8.0"

decompose = "3.3.0"
decompose-essenty = "2.5.0"

koin = "4.0.2"
koin-ksp-compiler = "2.0.0"

datastore = "1.1.3"
room = "2.7.0-rc02"
sqlite = "2.5.0-rc02"

mxparser = "6.1.0"
coil3 = "3.1.0"
media3-exoplayer = "1.5.1"
media3-ui = "1.5.1"
compottie = "2.0.0-rc04"
webview-multiplatform = "1.9.40"
ktor = "3.1.0"
gson = "2.12.1"

ad-admob = "24.1.0"
#ad-mediation-vungle = "7.4.2.0"
#ad-mediation-unity = "4.13.0.0"
#ad-mediation-pangle = "6.4.0.6.0"
#ad-mediation-unity-ads = "4.13.0"
#ad-mediation-facebook = "6.18.0.0"
#ad-mediation-applovin = "13.0.1.0"
#ad-mediation-mintegral = "16.8.61.0"

firebase-crashlytics = "3.0.3"
google-services = "4.4.2"
#firebaseBom = "33.10.0"
gitlive-firebase = "2.1.0"
desugar = "2.1.5"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }
#androidx-foundation-layout-android = { module = "androidx.compose.foundation:foundation-layout-android", version.ref = "androidx-foundation-layout-android" }
#androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
#androidx-material = { module = "com.google.android.material:material", version.ref = "androidx-material" }
#androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
#androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso-core" }
#androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }

#junit = { module = "junit:junit", version.ref = "junit" }

#kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
#kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

compose-shadow = { module = "com.adamglin:compose-shadow", version.ref = "compose-shadow" }

#kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
decompose-lifecycle-coroutines = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.ref = "decompose-essenty" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-ksp-compiler" }

datastore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

math-parser = { module = "org.mariuszgromada.math:MathParser.org-mXparser", version.ref = "mxparser" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-exoplayer" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3-ui" }

coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil3-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coil3" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
#compottie-dot = { module = "io.github.alexzhirkevich:compottie-dot", version.ref = "compottie" }
#compottie-network = { module = "io.github.alexzhirkevich:compottie-network", version.ref = "compottie" }
#compottie-resources = { module = "io.github.alexzhirkevich:compottie-resources", version.ref = "compottie" }

webview-multiplatform = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "webview-multiplatform" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
#ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
#ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

ad-core = { module = "com.google.android.gms:play-services-ads", version.ref = "ad-admob" }
#ad-mediation-unity = { module = "com.google.ads.mediation:unity", version.ref = "ad-mediation-unity" }
#ad-mediation-vungle = { module = "com.google.ads.mediation:vungle", version.ref = "ad-mediation-vungle" }
#ad-mediation-pangle = { module = "com.google.ads.mediation:pangle", version.ref = "ad-mediation-pangle" }
#ad-mediation-unity-ads = { module = "com.unity3d.ads:unity-ads", version.ref = "ad-mediation-unity-ads" }
#ad-mediation-facebook = { module = "com.google.ads.mediation:facebook", version.ref = "ad-mediation-facebook" }
#ad-mediation-applovin = { module = "com.google.ads.mediation:applovin", version.ref = "ad-mediation-applovin" }
#ad-mediation-mintegral = { module = "com.google.ads.mediation:mintegral", version.ref = "ad-mediation-mintegral" }

#firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
#firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
#firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
#firebase-config = { module = "com.google.firebase:firebase-config-ktx" }

gitlive-firebase-crashlytics = { module = "dev.gitlive:firebase-crashlytics", version.ref = "gitlive-firebase" }
gitlive-firebase-analytics = { module = "dev.gitlive:firebase-analytics", version.ref = "gitlive-firebase" }
gitlive-firebase-config = { module = "dev.gitlive:firebase-config", version.ref = "gitlive-firebase" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }

room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
admob = [
    "ad-core",
    #"ad-mediation-facebook",
    #"ad-mediation-mintegral",
    #"ad-mediation-pangle",
    #"ad-mediation-unity-ads",
    #"ad-mediation-unity",
    #"ad-mediation-applovin",
    #"ad-mediation-vungle",
]