[versions]
android-compileSdk = "35"
android-targetSdk = "35"
android-minSdk = "24"

kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"
agp = "8.8.1"

compose-multiplatform = "1.7.0"
compose-activity = "1.10.0"

androidx-appcompat = "1.7.0"
androidx-lifecycle = "2.8.4"
androidx-splashscreen = "1.0.1"
#androidx-foundation-layout-android = "1.7.8"
#androidx-core-ktx = "1.15.0"
#androidx-material = "1.12.0"
#androidx-constraintlayout = "2.2.0"
#androidx-espresso-core = "3.6.1"
#androidx-test-junit = "1.2.1"

#junit = "4.13.2"

kotlinx-collections = "0.3.8"
kotlinx-serialization = "1.8.0"

decompose = "3.1.0"
decompose-essenty = "2.4.0"

koin = "4.0.1"
koin-annotations = "1.4.0"
koin-ksp-compiler = "1.4.0"

datastore = "1.1.2"
room = "2.7.0-beta01"

mxparser = "6.1.0"
coil3 = "3.0.4"
mediaplayer = "2.0.6"
compottie = "2.0.0-rc04"
webview-multiplatform = "1.9.40"
ktor = "3.1.0"

ad-admob = "23.6.0"
#ad-mediation-vungle = "7.4.2.0"
#ad-mediation-unity = "4.13.0.0"
#ad-mediation-pangle = "6.4.0.6.0"
#ad-mediation-unity-ads = "4.13.0"
#ad-mediation-facebook = "6.18.0.0"
#ad-mediation-applovin = "13.0.1.0"
#ad-mediation-mintegral = "16.8.61.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-splashscreen" }
#androidx-foundation-layout-android = { group = "androidx.compose.foundation", name = "foundation-layout-android", version.ref = "androidx-foundation-layout-android" }
#androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
#androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
#androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
#androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
#androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }

#junit = { group = "junit", name = "junit", version.ref = "junit" }

#kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
#kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

kotlinx-collections = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-extensions-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }
decompose-lifecycle-coroutines = { group = "com.arkivanov.essenty", name = "lifecycle-coroutines", version.ref = "decompose-essenty" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-annotations" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-ksp-compiler" }

datastore = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "datastore" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

math-parser = { group = "org.mariuszgromada.math", name = "MathParser.org-mXparser", version.ref = "mxparser" }
coil3-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil3" }
mediaplayer = { module = "io.github.khubaibkhan4:mediaplayer-kmp", version.ref = "mediaplayer" }

compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
#compottie-dot = { module = "io.github.alexzhirkevich:compottie-dot", version.ref = "compottie" }
#compottie-network = { module = "io.github.alexzhirkevich:compottie-network", version.ref = "compottie" }
#compottie-resources = { module = "io.github.alexzhirkevich:compottie-resources", version.ref = "compottie" }

webview-multiplatform = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "webview-multiplatform" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
#ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
#ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

ad-core = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "ad-admob" }
#ad-mediation-unity = { group = "com.google.ads.mediation", name = "unity", version.ref = "ad-mediation-unity" }
#ad-mediation-vungle = { group = "com.google.ads.mediation", name = "vungle", version.ref = "ad-mediation-vungle" }
#ad-mediation-pangle = { group = "com.google.ads.mediation", name = "pangle", version.ref = "ad-mediation-pangle" }
#ad-mediation-unity-ads = { group = "com.unity3d.ads", name = "unity-ads", version.ref = "ad-mediation-unity-ads" }
#ad-mediation-facebook = { group = "com.google.ads.mediation", name = "facebook", version.ref = "ad-mediation-facebook" }
#ad-mediation-applovin = { group = "com.google.ads.mediation", name = "applovin", version.ref = "ad-mediation-applovin" }
#ad-mediation-mintegral = { group = "com.google.ads.mediation", name = "mintegral", version.ref = "ad-mediation-mintegral" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
admob = [
    "ad-core",
    #"ad-mediation-facebook",
    #"ad-mediation-mintegral",
    #"ad-mediation-pangle",
    #"ad-mediation-unity-ads",
    #"ad-mediation-unity",
    #"ad-mediation-applovin",
    #"ad-mediation-vungle",
]